version: '3.4'
services:
  webserver:
    image: 355982936287.dkr.ecr.us-east-2.amazonaws.com/webserver
    #  volumes:
    #    - /var/run/docker.sock:/var/run/docker.sock:ro
    #    - /swarm-keys:/root/.ssh
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      restart_policy:
        condition: on-failure
    ports:
      - 9999:9999
    command: ["go", "run", "main.go"]


  #    placement:
  #      constraints:
  #        - node.role==manager